# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = F:\Programs\CMake\bin\cmake.exe

# The command to remove a file.
RM = F:\Programs\CMake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "F:\Uni Files\UMSATS\Avionics_PC-Tools_V2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "F:\Uni Files\UMSATS\Avionics_PC-Tools_V2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	F:\Programs\CMake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	F:\Programs\CMake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "F:\Uni Files\UMSATS\Avionics_PC-Tools_V2\CMakeFiles" "F:\Uni Files\UMSATS\Avionics_PC-Tools_V2\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "F:\Uni Files\UMSATS\Avionics_PC-Tools_V2\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named avionics-pc-tools-gui

# Build rule for target.
avionics-pc-tools-gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 avionics-pc-tools-gui
.PHONY : avionics-pc-tools-gui

# fast build rule for target.
avionics-pc-tools-gui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/build
.PHONY : avionics-pc-tools-gui/fast

#=============================================================================
# Target rules for targets named avionics-pc-tools-gui_autogen

# Build rule for target.
avionics-pc-tools-gui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 avionics-pc-tools-gui_autogen
.PHONY : avionics-pc-tools-gui_autogen

# fast build rule for target.
avionics-pc-tools-gui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui_autogen.dir\build.make CMakeFiles/avionics-pc-tools-gui_autogen.dir/build
.PHONY : avionics-pc-tools-gui_autogen/fast

#=============================================================================
# Target rules for targets named serial

# Build rule for target.
serial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 serial
.PHONY : serial

# fast build rule for target.
serial/fast:
	$(MAKE) $(MAKESILENT) -f src-cpp\serial\CMakeFiles\serial.dir\build.make src-cpp/serial/CMakeFiles/serial.dir/build
.PHONY : serial/fast

#=============================================================================
# Target rules for targets named serial_autogen

# Build rule for target.
serial_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 serial_autogen
.PHONY : serial_autogen

# fast build rule for target.
serial_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src-cpp\serial\CMakeFiles\serial_autogen.dir\build.make src-cpp/serial/CMakeFiles/serial_autogen.dir/build
.PHONY : serial_autogen/fast

#=============================================================================
# Target rules for targets named quat_lib

# Build rule for target.
quat_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 quat_lib
.PHONY : quat_lib

# fast build rule for target.
quat_lib/fast:
	$(MAKE) $(MAKESILENT) -f src-cpp\widgets\graphics\cube\CMakeFiles\quat_lib.dir\build.make src-cpp/widgets/graphics/cube/CMakeFiles/quat_lib.dir/build
.PHONY : quat_lib/fast

#=============================================================================
# Target rules for targets named cube

# Build rule for target.
cube: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 cube
.PHONY : cube

# fast build rule for target.
cube/fast:
	$(MAKE) $(MAKESILENT) -f src-cpp\widgets\graphics\cube\CMakeFiles\cube.dir\build.make src-cpp/widgets/graphics/cube/CMakeFiles/cube.dir/build
.PHONY : cube/fast

#=============================================================================
# Target rules for targets named quat_lib_autogen

# Build rule for target.
quat_lib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 quat_lib_autogen
.PHONY : quat_lib_autogen

# fast build rule for target.
quat_lib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src-cpp\widgets\graphics\cube\CMakeFiles\quat_lib_autogen.dir\build.make src-cpp/widgets/graphics/cube/CMakeFiles/quat_lib_autogen.dir/build
.PHONY : quat_lib_autogen/fast

#=============================================================================
# Target rules for targets named cube_autogen

# Build rule for target.
cube_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 cube_autogen
.PHONY : cube_autogen

# fast build rule for target.
cube_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src-cpp\widgets\graphics\cube\CMakeFiles\cube_autogen.dir\build.make src-cpp/widgets/graphics/cube/CMakeFiles/cube_autogen.dir/build
.PHONY : cube_autogen/fast

avionics-pc-tools-gui_autogen/mocs_compilation.obj: avionics-pc-tools-gui_autogen/mocs_compilation.cpp.obj
.PHONY : avionics-pc-tools-gui_autogen/mocs_compilation.obj

# target to build an object file
avionics-pc-tools-gui_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/avionics-pc-tools-gui_autogen/mocs_compilation.cpp.obj
.PHONY : avionics-pc-tools-gui_autogen/mocs_compilation.cpp.obj

avionics-pc-tools-gui_autogen/mocs_compilation.i: avionics-pc-tools-gui_autogen/mocs_compilation.cpp.i
.PHONY : avionics-pc-tools-gui_autogen/mocs_compilation.i

# target to preprocess a source file
avionics-pc-tools-gui_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/avionics-pc-tools-gui_autogen/mocs_compilation.cpp.i
.PHONY : avionics-pc-tools-gui_autogen/mocs_compilation.cpp.i

avionics-pc-tools-gui_autogen/mocs_compilation.s: avionics-pc-tools-gui_autogen/mocs_compilation.cpp.s
.PHONY : avionics-pc-tools-gui_autogen/mocs_compilation.s

# target to generate assembly for a file
avionics-pc-tools-gui_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/avionics-pc-tools-gui_autogen/mocs_compilation.cpp.s
.PHONY : avionics-pc-tools-gui_autogen/mocs_compilation.cpp.s

src-cpp/dialogs/FlightDataFormatDialog.obj: src-cpp/dialogs/FlightDataFormatDialog.cpp.obj
.PHONY : src-cpp/dialogs/FlightDataFormatDialog.obj

# target to build an object file
src-cpp/dialogs/FlightDataFormatDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/dialogs/FlightDataFormatDialog.cpp.obj
.PHONY : src-cpp/dialogs/FlightDataFormatDialog.cpp.obj

src-cpp/dialogs/FlightDataFormatDialog.i: src-cpp/dialogs/FlightDataFormatDialog.cpp.i
.PHONY : src-cpp/dialogs/FlightDataFormatDialog.i

# target to preprocess a source file
src-cpp/dialogs/FlightDataFormatDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/dialogs/FlightDataFormatDialog.cpp.i
.PHONY : src-cpp/dialogs/FlightDataFormatDialog.cpp.i

src-cpp/dialogs/FlightDataFormatDialog.s: src-cpp/dialogs/FlightDataFormatDialog.cpp.s
.PHONY : src-cpp/dialogs/FlightDataFormatDialog.s

# target to generate assembly for a file
src-cpp/dialogs/FlightDataFormatDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/dialogs/FlightDataFormatDialog.cpp.s
.PHONY : src-cpp/dialogs/FlightDataFormatDialog.cpp.s

src-cpp/emulation/DataFeeder.obj: src-cpp/emulation/DataFeeder.cpp.obj
.PHONY : src-cpp/emulation/DataFeeder.obj

# target to build an object file
src-cpp/emulation/DataFeeder.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/DataFeeder.cpp.obj
.PHONY : src-cpp/emulation/DataFeeder.cpp.obj

src-cpp/emulation/DataFeeder.i: src-cpp/emulation/DataFeeder.cpp.i
.PHONY : src-cpp/emulation/DataFeeder.i

# target to preprocess a source file
src-cpp/emulation/DataFeeder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/DataFeeder.cpp.i
.PHONY : src-cpp/emulation/DataFeeder.cpp.i

src-cpp/emulation/DataFeeder.s: src-cpp/emulation/DataFeeder.cpp.s
.PHONY : src-cpp/emulation/DataFeeder.s

# target to generate assembly for a file
src-cpp/emulation/DataFeeder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/DataFeeder.cpp.s
.PHONY : src-cpp/emulation/DataFeeder.cpp.s

src-cpp/emulation/EmulationController.obj: src-cpp/emulation/EmulationController.cpp.obj
.PHONY : src-cpp/emulation/EmulationController.obj

# target to build an object file
src-cpp/emulation/EmulationController.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/EmulationController.cpp.obj
.PHONY : src-cpp/emulation/EmulationController.cpp.obj

src-cpp/emulation/EmulationController.i: src-cpp/emulation/EmulationController.cpp.i
.PHONY : src-cpp/emulation/EmulationController.i

# target to preprocess a source file
src-cpp/emulation/EmulationController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/EmulationController.cpp.i
.PHONY : src-cpp/emulation/EmulationController.cpp.i

src-cpp/emulation/EmulationController.s: src-cpp/emulation/EmulationController.cpp.s
.PHONY : src-cpp/emulation/EmulationController.s

# target to generate assembly for a file
src-cpp/emulation/EmulationController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/EmulationController.cpp.s
.PHONY : src-cpp/emulation/EmulationController.cpp.s

src-cpp/emulation/EventDetector.obj: src-cpp/emulation/EventDetector.cpp.obj
.PHONY : src-cpp/emulation/EventDetector.obj

# target to build an object file
src-cpp/emulation/EventDetector.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/EventDetector.cpp.obj
.PHONY : src-cpp/emulation/EventDetector.cpp.obj

src-cpp/emulation/EventDetector.i: src-cpp/emulation/EventDetector.cpp.i
.PHONY : src-cpp/emulation/EventDetector.i

# target to preprocess a source file
src-cpp/emulation/EventDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/EventDetector.cpp.i
.PHONY : src-cpp/emulation/EventDetector.cpp.i

src-cpp/emulation/EventDetector.s: src-cpp/emulation/EventDetector.cpp.s
.PHONY : src-cpp/emulation/EventDetector.s

# target to generate assembly for a file
src-cpp/emulation/EventDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/emulation/EventDetector.cpp.s
.PHONY : src-cpp/emulation/EventDetector.cpp.s

src-cpp/main.obj: src-cpp/main.cpp.obj
.PHONY : src-cpp/main.obj

# target to build an object file
src-cpp/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/main.cpp.obj
.PHONY : src-cpp/main.cpp.obj

src-cpp/main.i: src-cpp/main.cpp.i
.PHONY : src-cpp/main.i

# target to preprocess a source file
src-cpp/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/main.cpp.i
.PHONY : src-cpp/main.cpp.i

src-cpp/main.s: src-cpp/main.cpp.s
.PHONY : src-cpp/main.s

# target to generate assembly for a file
src-cpp/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/main.cpp.s
.PHONY : src-cpp/main.cpp.s

src-cpp/utilities/ChartDialogUtils.obj: src-cpp/utilities/ChartDialogUtils.cpp.obj
.PHONY : src-cpp/utilities/ChartDialogUtils.obj

# target to build an object file
src-cpp/utilities/ChartDialogUtils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/utilities/ChartDialogUtils.cpp.obj
.PHONY : src-cpp/utilities/ChartDialogUtils.cpp.obj

src-cpp/utilities/ChartDialogUtils.i: src-cpp/utilities/ChartDialogUtils.cpp.i
.PHONY : src-cpp/utilities/ChartDialogUtils.i

# target to preprocess a source file
src-cpp/utilities/ChartDialogUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/utilities/ChartDialogUtils.cpp.i
.PHONY : src-cpp/utilities/ChartDialogUtils.cpp.i

src-cpp/utilities/ChartDialogUtils.s: src-cpp/utilities/ChartDialogUtils.cpp.s
.PHONY : src-cpp/utilities/ChartDialogUtils.s

# target to generate assembly for a file
src-cpp/utilities/ChartDialogUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/utilities/ChartDialogUtils.cpp.s
.PHONY : src-cpp/utilities/ChartDialogUtils.cpp.s

src-cpp/utilities/QDirFinder.obj: src-cpp/utilities/QDirFinder.cpp.obj
.PHONY : src-cpp/utilities/QDirFinder.obj

# target to build an object file
src-cpp/utilities/QDirFinder.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/utilities/QDirFinder.cpp.obj
.PHONY : src-cpp/utilities/QDirFinder.cpp.obj

src-cpp/utilities/QDirFinder.i: src-cpp/utilities/QDirFinder.cpp.i
.PHONY : src-cpp/utilities/QDirFinder.i

# target to preprocess a source file
src-cpp/utilities/QDirFinder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/utilities/QDirFinder.cpp.i
.PHONY : src-cpp/utilities/QDirFinder.cpp.i

src-cpp/utilities/QDirFinder.s: src-cpp/utilities/QDirFinder.cpp.s
.PHONY : src-cpp/utilities/QDirFinder.s

# target to generate assembly for a file
src-cpp/utilities/QDirFinder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/utilities/QDirFinder.cpp.s
.PHONY : src-cpp/utilities/QDirFinder.cpp.s

src-cpp/widgets/DebuggingToolsWidget.obj: src-cpp/widgets/DebuggingToolsWidget.cpp.obj
.PHONY : src-cpp/widgets/DebuggingToolsWidget.obj

# target to build an object file
src-cpp/widgets/DebuggingToolsWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/DebuggingToolsWidget.cpp.obj
.PHONY : src-cpp/widgets/DebuggingToolsWidget.cpp.obj

src-cpp/widgets/DebuggingToolsWidget.i: src-cpp/widgets/DebuggingToolsWidget.cpp.i
.PHONY : src-cpp/widgets/DebuggingToolsWidget.i

# target to preprocess a source file
src-cpp/widgets/DebuggingToolsWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/DebuggingToolsWidget.cpp.i
.PHONY : src-cpp/widgets/DebuggingToolsWidget.cpp.i

src-cpp/widgets/DebuggingToolsWidget.s: src-cpp/widgets/DebuggingToolsWidget.cpp.s
.PHONY : src-cpp/widgets/DebuggingToolsWidget.s

# target to generate assembly for a file
src-cpp/widgets/DebuggingToolsWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/DebuggingToolsWidget.cpp.s
.PHONY : src-cpp/widgets/DebuggingToolsWidget.cpp.s

src-cpp/widgets/FlightEmulationWidget.obj: src-cpp/widgets/FlightEmulationWidget.cpp.obj
.PHONY : src-cpp/widgets/FlightEmulationWidget.obj

# target to build an object file
src-cpp/widgets/FlightEmulationWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/FlightEmulationWidget.cpp.obj
.PHONY : src-cpp/widgets/FlightEmulationWidget.cpp.obj

src-cpp/widgets/FlightEmulationWidget.i: src-cpp/widgets/FlightEmulationWidget.cpp.i
.PHONY : src-cpp/widgets/FlightEmulationWidget.i

# target to preprocess a source file
src-cpp/widgets/FlightEmulationWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/FlightEmulationWidget.cpp.i
.PHONY : src-cpp/widgets/FlightEmulationWidget.cpp.i

src-cpp/widgets/FlightEmulationWidget.s: src-cpp/widgets/FlightEmulationWidget.cpp.s
.PHONY : src-cpp/widgets/FlightEmulationWidget.s

# target to generate assembly for a file
src-cpp/widgets/FlightEmulationWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/FlightEmulationWidget.cpp.s
.PHONY : src-cpp/widgets/FlightEmulationWidget.cpp.s

src-cpp/widgets/OnBoardSensorsTestWidget.obj: src-cpp/widgets/OnBoardSensorsTestWidget.cpp.obj
.PHONY : src-cpp/widgets/OnBoardSensorsTestWidget.obj

# target to build an object file
src-cpp/widgets/OnBoardSensorsTestWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/OnBoardSensorsTestWidget.cpp.obj
.PHONY : src-cpp/widgets/OnBoardSensorsTestWidget.cpp.obj

src-cpp/widgets/OnBoardSensorsTestWidget.i: src-cpp/widgets/OnBoardSensorsTestWidget.cpp.i
.PHONY : src-cpp/widgets/OnBoardSensorsTestWidget.i

# target to preprocess a source file
src-cpp/widgets/OnBoardSensorsTestWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/OnBoardSensorsTestWidget.cpp.i
.PHONY : src-cpp/widgets/OnBoardSensorsTestWidget.cpp.i

src-cpp/widgets/OnBoardSensorsTestWidget.s: src-cpp/widgets/OnBoardSensorsTestWidget.cpp.s
.PHONY : src-cpp/widgets/OnBoardSensorsTestWidget.s

# target to generate assembly for a file
src-cpp/widgets/OnBoardSensorsTestWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/OnBoardSensorsTestWidget.cpp.s
.PHONY : src-cpp/widgets/OnBoardSensorsTestWidget.cpp.s

src-cpp/widgets/SerialPortSelectorWidget.obj: src-cpp/widgets/SerialPortSelectorWidget.cpp.obj
.PHONY : src-cpp/widgets/SerialPortSelectorWidget.obj

# target to build an object file
src-cpp/widgets/SerialPortSelectorWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/SerialPortSelectorWidget.cpp.obj
.PHONY : src-cpp/widgets/SerialPortSelectorWidget.cpp.obj

src-cpp/widgets/SerialPortSelectorWidget.i: src-cpp/widgets/SerialPortSelectorWidget.cpp.i
.PHONY : src-cpp/widgets/SerialPortSelectorWidget.i

# target to preprocess a source file
src-cpp/widgets/SerialPortSelectorWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/SerialPortSelectorWidget.cpp.i
.PHONY : src-cpp/widgets/SerialPortSelectorWidget.cpp.i

src-cpp/widgets/SerialPortSelectorWidget.s: src-cpp/widgets/SerialPortSelectorWidget.cpp.s
.PHONY : src-cpp/widgets/SerialPortSelectorWidget.s

# target to generate assembly for a file
src-cpp/widgets/SerialPortSelectorWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/SerialPortSelectorWidget.cpp.s
.PHONY : src-cpp/widgets/SerialPortSelectorWidget.cpp.s

src-cpp/widgets/TerminalWidget.obj: src-cpp/widgets/TerminalWidget.cpp.obj
.PHONY : src-cpp/widgets/TerminalWidget.obj

# target to build an object file
src-cpp/widgets/TerminalWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/TerminalWidget.cpp.obj
.PHONY : src-cpp/widgets/TerminalWidget.cpp.obj

src-cpp/widgets/TerminalWidget.i: src-cpp/widgets/TerminalWidget.cpp.i
.PHONY : src-cpp/widgets/TerminalWidget.i

# target to preprocess a source file
src-cpp/widgets/TerminalWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/TerminalWidget.cpp.i
.PHONY : src-cpp/widgets/TerminalWidget.cpp.i

src-cpp/widgets/TerminalWidget.s: src-cpp/widgets/TerminalWidget.cpp.s
.PHONY : src-cpp/widgets/TerminalWidget.s

# target to generate assembly for a file
src-cpp/widgets/TerminalWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/widgets/TerminalWidget.cpp.s
.PHONY : src-cpp/widgets/TerminalWidget.cpp.s

src-cpp/windows/MainWindow.obj: src-cpp/windows/MainWindow.cpp.obj
.PHONY : src-cpp/windows/MainWindow.obj

# target to build an object file
src-cpp/windows/MainWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/windows/MainWindow.cpp.obj
.PHONY : src-cpp/windows/MainWindow.cpp.obj

src-cpp/windows/MainWindow.i: src-cpp/windows/MainWindow.cpp.i
.PHONY : src-cpp/windows/MainWindow.i

# target to preprocess a source file
src-cpp/windows/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/windows/MainWindow.cpp.i
.PHONY : src-cpp/windows/MainWindow.cpp.i

src-cpp/windows/MainWindow.s: src-cpp/windows/MainWindow.cpp.s
.PHONY : src-cpp/windows/MainWindow.s

# target to generate assembly for a file
src-cpp/windows/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\avionics-pc-tools-gui.dir\build.make CMakeFiles/avionics-pc-tools-gui.dir/src-cpp/windows/MainWindow.cpp.s
.PHONY : src-cpp/windows/MainWindow.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... avionics-pc-tools-gui_autogen
	@echo ... cube_autogen
	@echo ... quat_lib_autogen
	@echo ... serial_autogen
	@echo ... avionics-pc-tools-gui
	@echo ... cube
	@echo ... quat_lib
	@echo ... serial
	@echo ... avionics-pc-tools-gui_autogen/mocs_compilation.obj
	@echo ... avionics-pc-tools-gui_autogen/mocs_compilation.i
	@echo ... avionics-pc-tools-gui_autogen/mocs_compilation.s
	@echo ... src-cpp/dialogs/FlightDataFormatDialog.obj
	@echo ... src-cpp/dialogs/FlightDataFormatDialog.i
	@echo ... src-cpp/dialogs/FlightDataFormatDialog.s
	@echo ... src-cpp/emulation/DataFeeder.obj
	@echo ... src-cpp/emulation/DataFeeder.i
	@echo ... src-cpp/emulation/DataFeeder.s
	@echo ... src-cpp/emulation/EmulationController.obj
	@echo ... src-cpp/emulation/EmulationController.i
	@echo ... src-cpp/emulation/EmulationController.s
	@echo ... src-cpp/emulation/EventDetector.obj
	@echo ... src-cpp/emulation/EventDetector.i
	@echo ... src-cpp/emulation/EventDetector.s
	@echo ... src-cpp/main.obj
	@echo ... src-cpp/main.i
	@echo ... src-cpp/main.s
	@echo ... src-cpp/utilities/ChartDialogUtils.obj
	@echo ... src-cpp/utilities/ChartDialogUtils.i
	@echo ... src-cpp/utilities/ChartDialogUtils.s
	@echo ... src-cpp/utilities/QDirFinder.obj
	@echo ... src-cpp/utilities/QDirFinder.i
	@echo ... src-cpp/utilities/QDirFinder.s
	@echo ... src-cpp/widgets/DebuggingToolsWidget.obj
	@echo ... src-cpp/widgets/DebuggingToolsWidget.i
	@echo ... src-cpp/widgets/DebuggingToolsWidget.s
	@echo ... src-cpp/widgets/FlightEmulationWidget.obj
	@echo ... src-cpp/widgets/FlightEmulationWidget.i
	@echo ... src-cpp/widgets/FlightEmulationWidget.s
	@echo ... src-cpp/widgets/OnBoardSensorsTestWidget.obj
	@echo ... src-cpp/widgets/OnBoardSensorsTestWidget.i
	@echo ... src-cpp/widgets/OnBoardSensorsTestWidget.s
	@echo ... src-cpp/widgets/SerialPortSelectorWidget.obj
	@echo ... src-cpp/widgets/SerialPortSelectorWidget.i
	@echo ... src-cpp/widgets/SerialPortSelectorWidget.s
	@echo ... src-cpp/widgets/TerminalWidget.obj
	@echo ... src-cpp/widgets/TerminalWidget.i
	@echo ... src-cpp/widgets/TerminalWidget.s
	@echo ... src-cpp/windows/MainWindow.obj
	@echo ... src-cpp/windows/MainWindow.i
	@echo ... src-cpp/windows/MainWindow.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

